// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmemxomankxphkwequbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZW14b21hbmt4cGhrd2VxdWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDY2MjIsImV4cCI6MjA1Mjk4MjYyMn0.fxL2Lkr-r2aj3AlmdqY0Oik-gPohX90JVbY0JKDWqHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);